services:
  db:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  postgres_data:
